services:
  pasarguard:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/pasarguard:/var/lib/pasarguard
