import PageHeader from '@/components/layout/page-header'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { $fetch } from '@/service/http'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle2, DatabaseBackup, Download, Loader2, LockKeyhole, RefreshCw, Send, ShieldCheck, Trash2, Upload } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { toast } from 'sonner'

interface BackupItem { id: number; created_at: string; filename: string; size: number; source_version?: string | null; source_db?: string | null; status: string; error_message?: string | null; backup_path: string; metadata_json?: Record<string, unknown> | null; created_by?: number | null; schedule_id?: number | null; telegram_enabled?: boolean }
interface BackupListResponse { items: BackupItem[]; total: number }
const formatSize = (size: number) => size < 1024 ? `${size} B` : size < 1024 ** 2 ? `${(size / 1024).toFixed(1)} KB` : size < 1024 ** 3 ? `${(size / 1024 ** 2).toFixed(1)} MB` : `${(size / 1024 ** 3).toFixed(1)} GB`

export default function BackupSettings() {
  const queryClient = useQueryClient(); const uploadRef = useRef<HTMLInputElement>(null)
  const [busy, setBusy] = useState(false); const [note, setNote] = useState(''); const [token, setToken] = useState(''); const [chatId, setChatId] = useState(''); const [checkingId, setCheckingId] = useState<number | null>(null)
  const { data, isLoading, isError, refetch } = useQuery({ queryKey: ['admin-backups'], queryFn: () => $fetch<BackupListResponse>('/api/admin/backup/list') })
  const { data: schedule, refetch: refetchSchedule } = useQuery({ queryKey: ['backup-schedule'], queryFn: () => $fetch<any>('/api/admin/backup/schedule') })
  const [scheduleEnabled, setScheduleEnabled] = useState(false); const [frequency, setFrequency] = useState('daily'); const [hour, setHour] = useState(2); const [minute, setMinute] = useState(0); const [weekday, setWeekday] = useState(1); const [dayOfMonth, setDayOfMonth] = useState(1); const [retention, setRetention] = useState(7); const [restoringId, setRestoringId] = useState<number | null>(null); const [restoreResult, setRestoreResult] = useState<any>(null)
  useEffect(() => { if (schedule) { setScheduleEnabled(schedule.enabled); setFrequency(schedule.frequency); setHour(schedule.hour); setMinute(schedule.minute); setWeekday(schedule.weekday ?? 1); setDayOfMonth(schedule.day_of_month ?? 1); setRetention(schedule.retention_count) } }, [schedule])
  const run = async (action: () => Promise<unknown>, success: string) => { setBusy(true); try { await action(); toast.success(success); await queryClient.invalidateQueries({ queryKey: ['admin-backups'] }) } catch (error: any) { toast.error(error?.data?.detail || error?.message || 'Backup operation failed') } finally { setBusy(false) } }
  const saveSchedule = () => run(async () => { const payload = { enabled: scheduleEnabled, frequency, hour, minute, weekday: frequency === 'weekly' ? weekday : null, day_of_month: frequency === 'monthly' ? dayOfMonth : null, retention_count: retention }; await $fetch('/api/admin/backup/schedule', { method: 'PUT', body: payload }); await refetchSchedule() }, 'Backup schedule saved')
  const createBackup = () => run(() => $fetch('/api/admin/backup/create', { method: 'POST', body: { note: note || null } }), 'Backup created successfully')
  const uploadBackup = async (file: File) => { setBusy(true); try { const form = new FormData(); form.append('file', file); await $fetch('/api/admin/backup/upload', { method: 'POST', body: form }); toast.success('Backup uploaded'); await queryClient.invalidateQueries({ queryKey: ['admin-backups'] }) } catch (error: any) { toast.error(error?.data?.detail || error?.message || 'Upload failed') } finally { setBusy(false); if (uploadRef.current) uploadRef.current.value = '' } }
  const checkBackup = async (id: number) => { setCheckingId(id); try { const result = await $fetch<{ valid: boolean; errors: string[] }>(`/api/admin/backup/check/${id}`, { method: 'POST' }); result.valid ? toast.success('Backup validation passed') : toast.error(result.errors.join('; ') || 'Backup validation failed'); await queryClient.invalidateQueries({ queryKey: ['admin-backups'] }) } catch (error: any) { toast.error(error?.data?.detail || error?.message || 'Validation failed') } finally { setCheckingId(null) } }
  const restoreToStaging = async (id: number) => { setRestoringId(id); setRestoreResult(null); try { const result = await $fetch<any>(`/api/admin/backup/restore/staging/${id}`, { method: 'POST' }); setRestoreResult(result); result.valid ? toast.success('Staging restore and migration passed') : toast.error('Staging restore completed with validation errors') } catch (error: any) { toast.error(error?.data?.detail || error?.message || 'Staging restore failed') } finally { setRestoringId(null) } }
  const deleteBackup = (id: number) => run(() => $fetch(`/api/admin/backup/${id}`, { method: 'DELETE' }), 'Backup deleted')
  const configureTelegram = () => { if (!token.trim() || !chatId.trim()) return void toast.error('Bot token and Chat ID are required'); run(() => $fetch('/api/admin/backup/configure-telegram', { method: 'POST', body: { telegram_bot_token: token, telegram_chat_id: chatId } }), 'Telegram backup notifications configured').then(() => setToken('')) }
  const items = data?.items ?? []

  return <div className="space-y-6">
    <PageHeader title="Backup & Restore" description="Manage encrypted backups, validation and Telegram notifications." />
    <Alert><ShieldCheck className="h-4 w-4" /><AlertDescription>Restore execution is staging-only in this phase. Production restore/apply is intentionally unavailable.</AlertDescription></Alert>
    <div className="grid gap-6 lg:grid-cols-2">
      <Card className="border-emerald-500/20"><CardHeader><CardTitle className="flex items-center gap-2"><DatabaseBackup className="h-5 w-5" /> Manual Backup</CardTitle><CardDescription>Create a database archive from the current runtime.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label htmlFor="backup-note">Note</Label><Input id="backup-note" value={note} onChange={e => setNote(e.target.value)} maxLength={500} placeholder="Optional backup note" /></div><Button onClick={createBackup} disabled={busy}><DatabaseBackup className="mr-2 h-4 w-4" />Create Backup</Button></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Upload className="h-5 w-5" /> Restore Preparation</CardTitle><CardDescription>Upload a ZIP and run the repository validation gate. No production restore is performed.</CardDescription></CardHeader><CardContent className="space-y-3"><input ref={uploadRef} type="file" accept=".zip,application/zip" className="hidden" onChange={e => e.target.files?.[0] && uploadBackup(e.target.files[0])} /><Button variant="outline" onClick={() => uploadRef.current?.click()} disabled={busy}><Upload className="mr-2 h-4 w-4" />Upload ZIP</Button><p className="text-sm text-muted-foreground">After upload, validate the archive, then run an isolated staging restore. The live database is never used as the restore target.</p></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Send className="h-5 w-5" /> Telegram</CardTitle><CardDescription>Bot credentials are encrypted before database storage and are never returned by the API.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label htmlFor="telegram-token">Bot Token</Label><Input id="telegram-token" type="password" autoComplete="new-password" value={token} onChange={e => setToken(e.target.value)} placeholder="••••••••" /></div><div className="space-y-2"><Label htmlFor="telegram-chat">Chat ID</Label><Input id="telegram-chat" value={chatId} onChange={e => setChatId(e.target.value)} placeholder="123456789" /></div><Button onClick={configureTelegram} disabled={busy}><LockKeyhole className="mr-2 h-4 w-4" />Save Encrypted Configuration</Button></CardContent></Card>
      <Card><CardHeader><CardTitle>Automatic Backup</CardTitle><CardDescription>Daily, weekly, monthly scheduling and retention controls.</CardDescription></CardHeader><CardContent><Alert><AlertDescription>Scheduler API and retention controls are not yet exposed by the backend. This UI intentionally does not fake those operations.</AlertDescription></Alert></CardContent></Card>
    </div>
    <Card><CardHeader className="flex-row items-center justify-between space-y-0"><div><CardTitle>Backup History</CardTitle><CardDescription>{data?.total ?? 0} records</CardDescription></div><Button variant="ghost" size="icon" onClick={() => refetch()} disabled={isLoading}><RefreshCw className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} /></Button></CardHeader><CardContent>
      {isError && <Alert variant="destructive"><AlertDescription>Unable to load backup history.</AlertDescription></Alert>}
      {isLoading ? <div className="flex items-center gap-2 py-8 text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />Loading backup history…</div> : items.length === 0 ? <div className="py-8 text-center text-muted-foreground">No backups yet.</div> : <div className="space-y-2">{items.map(item => <div key={item.id} className="flex flex-col gap-3 rounded-lg border p-4 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><div className="font-medium truncate">{item.filename}</div><div className="text-sm text-muted-foreground">{new Date(item.created_at).toLocaleString()} · {formatSize(item.size)} · {item.status}</div></div><div className="flex flex-wrap gap-2">{item.status === 'uploaded' && <Button size="sm" variant="outline" onClick={() => checkBackup(item.id)} disabled={checkingId === item.id}>{checkingId === item.id ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <CheckCircle2 className="mr-2 h-4 w-4" />}Validate</Button>}{['created','valid','uploaded'].includes(item.status) && <Button size="sm" variant="outline" onClick={() => restoreToStaging(item.id)} disabled={restoringId === item.id}>{restoringId === item.id ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <ShieldCheck className="mr-2 h-4 w-4" />}Staging Restore</Button>}<Button size="sm" variant="outline" disabled title="Download endpoint is not exposed by the current backend"><Download className="mr-2 h-4 w-4" />Download</Button><Button size="sm" variant="ghost" onClick={() => deleteBackup(item.id)} disabled={busy}><Trash2 className="h-4 w-4" /></Button></div></div>)}</div>}
    </CardContent></Card>{restoreResult && <Card><CardHeader><CardTitle>Last Staging Restore</CardTitle><CardDescription>Isolated restore result; the staging database was dropped after validation.</CardDescription></CardHeader><CardContent className="space-y-2 text-sm"><div>Result: <strong>{restoreResult.valid ? 'PASS' : 'FAIL'}</strong></div><div>Format: {restoreResult.source_format || 'unknown'} · Source: {restoreResult.source_product || 'unknown'}</div><div>Pre-upgrade rows: {JSON.stringify(restoreResult.pre_upgrade_counts)}</div><div>Post-upgrade rows: {JSON.stringify(restoreResult.post_upgrade_counts)}</div>{restoreResult.errors?.length > 0 && <Alert variant="destructive"><AlertDescription>{restoreResult.errors.join('; ')}</AlertDescription></Alert>}</CardContent></Card>}
  </div>
}
