from __future__ import annotations

import asyncio
import gzip
import os
import re
import shutil
import subprocess
import tarfile
import tempfile
import uuid
import zipfile
from dataclasses import dataclass
from pathlib import Path

import asyncpg
from alembic import command
from alembic.config import Config
from sqlalchemy.engine import URL, make_url

from app.migration.detector import BackupDetection, detect_backup


class MigrationSafetyError(RuntimeError):
    """Raised when a migration operation violates a safety invariant."""


STAGING_DB_PATTERN = re.compile(r"^manubisguard_migration_[0-9a-f]{12}$")
MAX_ARCHIVE_BYTES = 2 * 1024 * 1024 * 1024


@dataclass(frozen=True)
class StagingDatabase:
    database_name: str
    staging_url: str = ""
    _production_url: str = ""

    def __repr__(self) -> str:
        return f"StagingDatabase(database_name={self.database_name!r})"


def _postgres_url(url: str, database: str | None = None) -> URL:
    parsed = make_url(url)
    if not parsed.drivername.startswith("postgresql"):
        raise MigrationSafetyError("Migration staging requires PostgreSQL/TimescaleDB.")
    return parsed.set(database=database) if database is not None else parsed


def _asyncpg_kwargs(url: str, database: str | None = None) -> dict[str, object]:
    parsed = _postgres_url(url, database)
    sslmode = parsed.query.get("sslmode")
    if sslmode in {"verify-ca", "verify-full"}:
        raise MigrationSafetyError("verify-ca/verify-full requires an explicit SSL context.")
    kwargs = {
        "host": parsed.host,
        "port": parsed.port,
        "user": parsed.username,
        "password": parsed.password,
        "database": parsed.database,
    }
    if sslmode == "require":
        kwargs["ssl"] = True
    return {k: v for k, v in kwargs.items() if v is not None}


def _cli_args(url: str) -> list[str]:
    parsed = _postgres_url(url)
    if not parsed.database:
        raise MigrationSafetyError("PostgreSQL URL must contain a database name.")
    args: list[str] = []
    if parsed.host:
        args += ["--host", parsed.host]
    if parsed.port:
        args += ["--port", str(parsed.port)]
    if parsed.username:
        args += ["--username", parsed.username]
    args += ["--dbname", parsed.database]
    return args


def _cli_env(url: str) -> dict[str, str]:
    parsed = _postgres_url(url)
    env = os.environ.copy()
    if parsed.password is not None:
        env["PGPASSWORD"] = parsed.password
    if parsed.query.get("sslmode"):
        env["PGSSLMODE"] = str(parsed.query["sslmode"])
    env["PGAPPNAME"] = "manubisguard-migration"
    return env


def assert_staging_target(production_url: str, staging_url: str) -> None:
    production = _postgres_url(production_url)
    staging = _postgres_url(staging_url)
    if not staging.database:
        raise MigrationSafetyError("Staging URL must contain a database name.")
    if production.database == staging.database:
        raise MigrationSafetyError("Safety stop: staging database equals production database.")
    if production.host != staging.host or production.port != staging.port:
        raise MigrationSafetyError("Safety stop: staging server differs from production server.")
    if production.username != staging.username:
        raise MigrationSafetyError("Safety stop: staging database owner differs from production.")
    if not STAGING_DB_PATTERN.fullmatch(staging.database):
        raise MigrationSafetyError("Safety stop: database was not generated by the migration engine.")


async def _create_database(url: str, name: str) -> None:
    conn = await asyncpg.connect(**_asyncpg_kwargs(url, "postgres"))
    try:
        await conn.execute(f'CREATE DATABASE "{name}" TEMPLATE template0')
    finally:
        await conn.close()


async def _drop_database(url: str, name: str) -> None:
    conn = await asyncpg.connect(**_asyncpg_kwargs(url, "postgres"))
    try:
        await conn.execute(
            "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
            "WHERE datname = $1 AND pid <> pg_backend_pid()",
            name,
        )
        await conn.execute(f'DROP DATABASE IF EXISTS "{name}"')
    finally:
        await conn.close()


def create_staging_database(production_url: str) -> StagingDatabase:
    parsed = _postgres_url(production_url)
    if not parsed.database:
        raise MigrationSafetyError("Production PostgreSQL URL must contain a database name.")
    name = f"manubisguard_migration_{uuid.uuid4().hex[:12]}"
    asyncio.run(_create_database(production_url, name))
    staging_url = _postgres_url(production_url, name).render_as_string(hide_password=False)
    assert_staging_target(production_url, staging_url)
    return StagingDatabase(name, staging_url, production_url)


def drop_staging_database(staging: StagingDatabase) -> None:
    if not STAGING_DB_PATTERN.fullmatch(staging.database_name):
        raise MigrationSafetyError("Refusing to drop a non-engine staging database.")
    if not staging._production_url:
        raise MigrationSafetyError("Staging object is missing its protected production URL.")
    asyncio.run(_drop_database(staging._production_url, staging.database_name))


def _safe_extract_zip(src: Path, dst: Path) -> None:
    total = 0
    root = dst.resolve()
    with zipfile.ZipFile(src) as zf:
        for info in zf.infolist():
            if info.is_dir():
                continue
            mode = (info.external_attr >> 16) & 0o170000
            if mode in {0o120000} or (mode and mode != 0o100000):
                raise MigrationSafetyError("Archive contains a link or special file.")
            total += info.file_size
            if total > MAX_ARCHIVE_BYTES:
                raise MigrationSafetyError("Archive exceeds the safe extraction limit.")
            target = (dst / info.filename).resolve()
            if not target.is_relative_to(root):
                raise MigrationSafetyError("Archive contains a path traversal entry.")
            target.parent.mkdir(parents=True, exist_ok=True)
            with zf.open(info) as source, target.open("wb") as out:
                shutil.copyfileobj(source, out, 1024 * 1024)


def _safe_extract_tar(src: Path, dst: Path) -> None:
    total = 0
    root = dst.resolve()
    with tarfile.open(src, "r:*") as tf:
        members = tf.getmembers()
        for info in members:
            if not info.isfile():
                if not info.isdir():
                    raise MigrationSafetyError("Archive contains a link or special file.")
                continue
            total += info.size
            if total > MAX_ARCHIVE_BYTES:
                raise MigrationSafetyError("Archive exceeds the safe extraction limit.")
            target = (dst / info.name).resolve()
            if not target.is_relative_to(root):
                raise MigrationSafetyError("Archive contains a path traversal entry.")
        tf.extractall(dst, filter="data")


def _prepare_source(path: Path) -> tuple[Path, BackupDetection, tempfile.TemporaryDirectory[str] | None]:
    detection = detect_backup(path)
    if path.name.lower().endswith(".zip"):
        tmp = tempfile.TemporaryDirectory(prefix="manubisguard-migration-")
        root = Path(tmp.name)
        _safe_extract_zip(path, root)
        return _find_candidate(root), tmp
    if path.name.lower().endswith((".tar", ".tgz", ".tar.gz")):
        tmp = tempfile.TemporaryDirectory(prefix="manubisguard-migration-")
        root = Path(tmp.name)
        _safe_extract_tar(path, root)
        return _find_candidate(root), tmp
    return (path, detection), None


def _find_candidate(root: Path) -> tuple[Path, BackupDetection]:
    candidates: list[tuple[Path, BackupDetection]] = []
    for path in sorted(p for p in root.rglob("*") if p.is_file()):
        try:
            detection = detect_backup(path)
        except (OSError, ValueError, zipfile.BadZipFile, tarfile.TarError):
            continue
        if (
            detection.is_pasarguard
            and detection.confidence in {"high", "medium"}
            and detection.format in {"sql", "sql.gz", "pg_dump_custom"}
        ):
            candidates.append((path, detection))
    if not candidates:
        raise MigrationSafetyError("Archive contains no valid PasarGuard database backup.")
    if len(candidates) != 1:
        names = ", ".join(str(p.relative_to(root)) for p, _ in candidates[:8])
        raise MigrationSafetyError(f"Archive contains multiple database backups: {names}")
    return candidates[0]


def _run_psql(source: Path, url: str, timeout: int, compressed: bool) -> None:
    binary = shutil.which("psql")
    if not binary:
        raise MigrationSafetyError("psql is missing from the ManubisGuard runtime image.")
    proc = subprocess.Popen(
        [binary, *_cli_args(url), "--no-psqlrc", "--set", "ON_ERROR_STOP=1", "--single-transaction"],
        env=_cli_env(url),
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    assert proc.stdin is not None
    try:
        opener = gzip.open if compressed else open
        with opener(source, "rb") as stream:
            shutil.copyfileobj(stream, proc.stdin, 1024 * 1024)
        proc.stdin.close()
        proc.stdin = None
        stdout, stderr = proc.communicate(timeout=timeout)
    except BaseException:
        if proc.poll() is None:
            proc.kill()
        proc.wait(timeout=5)
        raise
    if proc.returncode:
        detail = (stderr or stdout or b"psql restore failed").decode("utf-8", errors="replace")[-4000:]
        raise MigrationSafetyError(f"psql restore failed in staging: {detail}")


def _inspect_pg_dump_custom(source: Path, timeout: int) -> BackupDetection:
    binary = shutil.which("pg_restore")
    if not binary:
        raise MigrationSafetyError("pg_restore is missing from the ManubisGuard runtime image.")
    result = subprocess.run(
        [binary, "--list", str(source)],
        env=_cli_env("postgresql://localhost/postgres"),
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )
    if result.returncode:
        detail = (result.stderr or result.stdout or "pg_restore inspection failed")[-4000:]
        raise MigrationSafetyError(f"pg_restore inspection failed: {detail}")

    sample = (result.stdout or "").lower()
    evidence = ["pg_restore TOC inspection completed"]
    marker_hits = [marker for marker in (
        "pasarguard",
        "pasar guard",
    ) if marker in sample]
    if marker_hits:
        evidence.extend(f"legacy marker in dump TOC: {marker}" for marker in marker_hits)
        product = "pasarguard"
        confidence = "high"
    elif all(table in sample for table in ("core_configs", "nodes", "alembic_version")):
        evidence.extend("schema markers found in pg_restore TOC" for _ in [0])
        product = "pasarguard"
        confidence = "medium"
    else:
        product = "unknown"
        confidence = "low"

    revision_match = re.search(
        r"alembic_version.*?([0-9a-z]{8,32})",
        sample,
        flags=re.DOTALL,
    )
    return BackupDetection(
        path=str(source),
        format="pg_dump_custom",
        source_product=product,
        confidence=confidence,
        evidence=tuple(dict.fromkeys(evidence)),
        schema_revision=revision_match.group(1) if revision_match else None,
        warnings=("Custom PostgreSQL dump was identified from its read-only TOC.",),
    )


def _run_pg_restore(source: Path, url: str, timeout: int) -> None:
    binary = shutil.which("pg_restore")
    if not binary:
        raise MigrationSafetyError("pg_restore is missing from the ManubisGuard runtime image.")
    result = subprocess.run(
        [
            binary,
            *_cli_args(url),
            "--exit-on-error",
            "--single-transaction",
            "--no-owner",
            "--no-privileges",
            str(source),
        ],
        env=_cli_env(url),
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )
    if result.returncode:
        detail = (result.stderr or result.stdout or "pg_restore failed")[-4000:]
        raise MigrationSafetyError(f"pg_restore failed in staging: {detail}")


def restore_backup_into_staging(
    backup_path: str | Path,
    staging: StagingDatabase,
    *,
    timeout: int = 900,
) -> BackupDetection:
    assert_staging_target(staging._production_url, staging.staging_url)
    path = Path(backup_path).expanduser().resolve()
    if not path.is_file():
        raise FileNotFoundError(path)
    source, detection, tmp = _prepare_source(path)
    try:
        if not detection.is_pasarguard or detection.confidence not in {"high", "medium"}:
            raise MigrationSafetyError("Backup is not positively identified as PasarGuard.")
        if detection.format == "sql":
            _run_psql(source, staging.staging_url, timeout, False)
        elif detection.format == "sql.gz":
            _run_psql(source, staging.staging_url, timeout, True)
        elif detection.format == "pg_dump_custom":
            inspected = _inspect_pg_dump_custom(source, min(timeout, 120))
            if not inspected.is_pasarguard or inspected.confidence not in {"high", "medium"}:
                raise MigrationSafetyError("Custom dump could not be positively identified as PasarGuard.")
            detection = inspected
            _run_pg_restore(source, staging.staging_url, timeout)
        else:
            raise MigrationSafetyError(f"Unsupported database restore format: {detection.format}")
        return detection
    finally:
        if tmp is not None:
            tmp.cleanup()


def upgrade_staging_database(
    staging: StagingDatabase,
    *,
    production_url: str,
    revision: str = "head",
) -> None:
    assert_staging_target(production_url, staging.staging_url)
    config = Config(str(Path(__file__).resolve().parents[2] / "alembic.ini"))
    config.set_main_option("sqlalchemy.url", staging.staging_url)
    config.attributes["manubisguard_migration_staging"] = True
    command.upgrade(config, revision)
