from __future__ import annotations

import gzip
import os
import re
import shutil
import subprocess
import tarfile
import tempfile
import uuid
import zipfile
from dataclasses import dataclass
from pathlib import Path

import asyncpg
from alembic import command
from alembic.config import Config
from sqlalchemy.engine import URL, make_url

from app.migration.async_utils import run_async
from app.migration.detector import BackupDetection, detect_backup
from app.migration.timescale import (
    TIMESCALEDB_CATALOG_SEED_CLEAR_SQL,
    filter_timescaledb_ddl_line,
)


class MigrationSafetyError(RuntimeError):
    """Raised when a migration operation violates a safety invariant."""


STAGING_DB_PATTERN = re.compile(r"^manubisguard_migration_[0-9a-f]{12}$")
CUTOVER_DB_PATTERN = re.compile(r"^manubisguard_cutover_[0-9a-f]{12}$")
ISOLATED_DB_PATTERN = re.compile(
    r"^manubisguard_(?:migration|cutover)_[0-9a-f]{12}$"
)
MAX_ARCHIVE_BYTES = 2 * 1024 * 1024 * 1024
MAX_SQL_INSPECT_BYTES = 1_200_000
SQL_COMPLETE_MARKER = "-- PostgreSQL database dump complete"


@dataclass(frozen=True)
class StagingDatabase:
    database_name: str
    staging_url: str = ""
    _production_url: str = ""

    def __repr__(self) -> str:
        return f"StagingDatabase(database_name={self.database_name!r})"


def _postgres_url(url: str, database: str | None = None) -> URL:
    parsed = make_url(url)
    if not parsed.drivername.startswith("postgresql"):
        raise MigrationSafetyError("Migration staging requires PostgreSQL/TimescaleDB.")
    return parsed.set(database=database) if database is not None else parsed


def _asyncpg_kwargs(url: str, database: str | None = None) -> dict[str, object]:
    parsed = _postgres_url(url, database)
    sslmode = parsed.query.get("sslmode")
    if sslmode in {"verify-ca", "verify-full"}:
        raise MigrationSafetyError("verify-ca/verify-full requires an explicit SSL context.")
    kwargs: dict[str, object] = {
        "host": parsed.host,
        "port": parsed.port,
        "user": parsed.username,
        "password": parsed.password,
        "database": parsed.database,
    }
    if sslmode == "require":
        kwargs["ssl"] = True
    return {k: v for k, v in kwargs.items() if v is not None}


def _cli_args(url: str) -> list[str]:
    parsed = _postgres_url(url)
    if not parsed.database:
        raise MigrationSafetyError("PostgreSQL URL must contain a database name.")
    args: list[str] = []
    if parsed.host:
        args += ["--host", parsed.host]
    if parsed.port:
        args += ["--port", str(parsed.port)]
    if parsed.username:
        args += ["--username", parsed.username]
    args += ["--dbname", parsed.database]
    return args


def _cli_env(url: str) -> dict[str, str]:
    parsed = _postgres_url(url)
    env = os.environ.copy()
    if parsed.password is not None:
        env["PGPASSWORD"] = parsed.password
    if parsed.query.get("sslmode"):
        env["PGSSLMODE"] = str(parsed.query["sslmode"])
    env["PGAPPNAME"] = "manubisguard-migration"
    return env


def _normalized_host(value: str | None) -> str | None:
    if value in {"127.0.0.1", "localhost", "::1"}:
        return "loopback"
    return value


def assert_staging_target(
    production_url: str,
    staging_url: str,
    *,
    allow_external_port: bool = False,
) -> None:
    """Enforce that a restore target is a generated isolated database.

    By default the target must be on the same PostgreSQL server/port/user as
    production, but the generated database name still keeps it isolated.
    A host-side temporary Docker Timescale instance uses the same loopback host
    and database user on a different localhost port, which is permitted only
    with allow_external_port=True.
    """
    production = _postgres_url(production_url)
    staging = _postgres_url(staging_url)
    if not staging.database:
        raise MigrationSafetyError("Staging URL must contain a database name.")
    if production.database == staging.database:
        raise MigrationSafetyError("Safety stop: staging database equals production database.")
    if _normalized_host(production.host) != _normalized_host(staging.host):
        raise MigrationSafetyError("Safety stop: staging server differs from production.")
    if production.username != staging.username:
        raise MigrationSafetyError("Safety stop: staging database owner differs from production.")
    if not ISOLATED_DB_PATTERN.fullmatch(staging.database):
        raise MigrationSafetyError("Safety stop: database was not generated by the migration engine.")
    if not allow_external_port and production.port != staging.port:
        raise MigrationSafetyError("Safety stop: staging port differs from production.")
    if allow_external_port:
        if _normalized_host(staging.host) != "loopback":
            raise MigrationSafetyError("External staging is allowed only on localhost.")
        if production.port == staging.port:
            raise MigrationSafetyError(
                "External staging must use a different localhost port from production."
            )


async def _create_database(url: str, name: str) -> None:
    conn = await asyncpg.connect(**_asyncpg_kwargs(url, "postgres"))
    try:
        await conn.execute(f'CREATE DATABASE "{name}" TEMPLATE template0')
    finally:
        await conn.close()


async def _drop_database(url: str, name: str) -> None:
    conn = await asyncpg.connect(**_asyncpg_kwargs(url, "postgres"))
    try:
        await conn.execute(
            "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
            "WHERE datname = $1 AND pid <> pg_backend_pid()",
            name,
        )
        await conn.execute(f'DROP DATABASE IF EXISTS "{name}"')
    finally:
        await conn.close()


def create_staging_database(production_url: str) -> StagingDatabase:
    parsed = _postgres_url(production_url)
    if not parsed.database:
        raise MigrationSafetyError("Production PostgreSQL URL must contain a database name.")
    name = f"manubisguard_migration_{uuid.uuid4().hex[:12]}"
    run_async(_create_database(production_url, name))
    staging_url = _postgres_url(production_url, name).render_as_string(hide_password=False)
    assert_staging_target(production_url, staging_url)
    return StagingDatabase(name, staging_url, production_url)


def drop_staging_database(staging: StagingDatabase) -> None:
    if not STAGING_DB_PATTERN.fullmatch(staging.database_name):
        raise MigrationSafetyError("Refusing to drop a non-engine staging database.")
    if not staging._production_url:
        raise MigrationSafetyError("Staging object is missing its protected production URL.")
    run_async(_drop_database(staging._production_url, staging.database_name))


def _safe_extract_zip(src: Path, dst: Path) -> None:
    total = 0
    root = dst.resolve()
    with zipfile.ZipFile(src) as zf:
        for info in zf.infolist():
            if info.is_dir():
                continue
            mode = (info.external_attr >> 16) & 0o170000
            if mode == 0o120000 or (mode and mode != 0o100000):
                raise MigrationSafetyError("Archive contains a link or special file.")
            total += info.file_size
            if total > MAX_ARCHIVE_BYTES:
                raise MigrationSafetyError("Archive exceeds the safe extraction limit.")
            target = (dst / info.filename).resolve()
            if not target.is_relative_to(root):
                raise MigrationSafetyError("Archive contains a path traversal entry.")
            target.parent.mkdir(parents=True, exist_ok=True)
            with zf.open(info) as source, target.open("wb") as out:
                shutil.copyfileobj(source, out, 1024 * 1024)


def _safe_extract_tar(src: Path, dst: Path) -> None:
    total = 0
    root = dst.resolve()
    with tarfile.open(src, "r:*") as tf:
        for info in tf.getmembers():
            if info.isfile():
                total += info.size
                if total > MAX_ARCHIVE_BYTES:
                    raise MigrationSafetyError("Archive exceeds the safe extraction limit.")
                target = (dst / info.name).resolve()
                if not target.is_relative_to(root):
                    raise MigrationSafetyError("Archive contains a path traversal entry.")
            elif not info.isdir():
                raise MigrationSafetyError("Archive contains a link or special file.")
        tf.extractall(dst, filter="data")


def _find_candidate(root: Path) -> tuple[Path, BackupDetection]:
    candidates: list[tuple[Path, BackupDetection]] = []
    for path in sorted(p for p in root.rglob("*") if p.is_file()):
        try:
            detection = detect_backup(path)
        except (OSError, ValueError, zipfile.BadZipFile, tarfile.TarError):
            continue
        if (
            detection.confidence in {"high", "medium"}
            and detection.format in {"sql", "sql.gz", "pg_dump_custom"}
        ):
            candidates.append((path, detection))
    if not candidates:
        raise MigrationSafetyError("Archive contains no valid PasarGuard database backup.")
    if len(candidates) != 1:
        names = ", ".join(str(p.relative_to(root)) for p, _ in candidates[:8])
        raise MigrationSafetyError(f"Archive contains multiple database backups: {names}")
    return candidates[0]


def _prepare_source(
    path: Path,
) -> tuple[Path, BackupDetection, tempfile.TemporaryDirectory[str] | None]:
    detection = detect_backup(path)
    if path.name.lower().endswith(".zip"):
        tmp = tempfile.TemporaryDirectory(prefix="manubisguard-migration-")
        root = Path(tmp.name)
        _safe_extract_zip(path, root)
        source, nested = _find_candidate(root)
        return source, nested, tmp
    if path.name.lower().endswith((".tar", ".tgz", ".tar.gz")):
        tmp = tempfile.TemporaryDirectory(prefix="manubisguard-migration-")
        root = Path(tmp.name)
        _safe_extract_tar(path, root)
        source, nested = _find_candidate(root)
        return source, nested, tmp
    return path, detection, None


def _read_sql_compatibility(path: Path) -> str:
    if path.name.lower().endswith(".gz"):
        with gzip.open(path, "rt", encoding="utf-8", errors="replace") as fh:
            head = fh.read(MAX_SQL_INSPECT_BYTES)
            try:
                fh.seek(max(0, fh.tell() - MAX_SQL_INSPECT_BYTES))
                tail = fh.read(MAX_SQL_INSPECT_BYTES)
            except (OSError, ValueError):
                tail = ""
        return head + "\n" + tail

    with path.open("rt", encoding="utf-8", errors="replace") as fh:
        head = fh.read(MAX_SQL_INSPECT_BYTES)
        try:
            fh.seek(max(0, path.stat().st_size - MAX_SQL_INSPECT_BYTES))
            tail = fh.read(MAX_SQL_INSPECT_BYTES)
        except OSError:
            tail = ""
    return head + "\n" + tail


def _assert_sql_dump_complete(source: Path) -> None:
    """Reject empty/truncated plain pg_dump files before restoring them."""
    if source.name.lower().endswith(".gz"):
        with gzip.open(source, "rt", encoding="utf-8", errors="replace") as fh:
            tail = ""
            for chunk in iter(lambda: fh.read(MAX_SQL_INSPECT_BYTES), ""):
                tail = chunk[-MAX_SQL_INSPECT_BYTES:]
        text = tail
    else:
        size = source.stat().st_size
        if size <= 0:
            raise MigrationSafetyError("SQL backup is empty.")
        with source.open("rt", encoding="utf-8", errors="replace") as fh:
            fh.seek(max(0, size - MAX_SQL_INSPECT_BYTES))
            text = fh.read(MAX_SQL_INSPECT_BYTES)
    if SQL_COMPLETE_MARKER not in text:
        raise MigrationSafetyError(
            "SQL backup does not contain the PostgreSQL completion marker; "
            "it may be truncated or incomplete."
        )


def _psql_query(url: str, sql: str, timeout: int = 60) -> str:
    binary = shutil.which("psql")
    if not binary:
        raise MigrationSafetyError("psql is missing from the ManubisGuard runtime image.")
    result = subprocess.run(
        [binary, *_cli_args(url), "--no-psqlrc", "--tuples-only", "--no-align", "--set", "ON_ERROR_STOP=1", "-c", sql],
        env=_cli_env(url),
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )
    output = (result.stdout or "") + (result.stderr or "")
    if result.returncode:
        raise MigrationSafetyError(output[-4000:] or "psql query failed.")
    return result.stdout.strip()


def _timescale_extension_version(url: str) -> str | None:
    try:
        value = _psql_query(
            url,
            "SELECT installed_version FROM pg_available_extensions WHERE name = 'timescaledb'",
            timeout=30,
        )
    except MigrationSafetyError:
        return None
    return value or None


def _backup_uses_timescaledb(source: Path, detection: BackupDetection) -> bool:
    if detection.format == "pg_dump_custom":
        inspected = _inspect_pg_dump_custom(source, 120)
        return "timescaledb" in "\n".join(inspected.evidence).lower() or "timescaledb" in getattr(
            inspected, "_toc", ""
        )
    return "timescaledb" in _read_sql_compatibility(source).lower()


def _timescale_seed_cleanup(url: str) -> None:
    _psql_query(url, TIMESCALEDB_CATALOG_SEED_CLEAR_SQL, timeout=120)


def _timescale_pre_restore(url: str) -> None:
    _psql_query(url, "CREATE EXTENSION IF NOT EXISTS timescaledb", timeout=120)
    _psql_query(url, "SELECT timescaledb_pre_restore()", timeout=120)
    _timescale_seed_cleanup(url)


def _timescale_post_restore(url: str) -> None:
    last_error = ""
    for _ in range(2):
        try:
            _psql_query(url, "SELECT timescaledb_post_restore()", timeout=120)
            return
        except MigrationSafetyError as exc:
            last_error = str(exc)
    raise MigrationSafetyError(
        "TimescaleDB post-restore finalization failed; staging remains isolated. "
        f"Last error: {last_error[-2000:]}"
    )


def _run_psql_restore(source: Path, url: str, *, compressed: bool, timeout: int) -> None:
    binary = shutil.which("psql")
    if not binary:
        raise MigrationSafetyError("psql is missing from the ManubisGuard runtime image.")
    proc = subprocess.Popen(
        [
            binary,
            *_cli_args(url),
            "--no-psqlrc",
            "--set",
            "ON_ERROR_STOP=1",
        ],
        env=_cli_env(url),
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    assert proc.stdin is not None
    try:
        opener = gzip.open if compressed else open
        with opener(source, "rb") as stream:
            shutil.copyfileobj(stream, proc.stdin, 1024 * 1024)
        proc.stdin.close()
        proc.stdin = None
        stdout, stderr = proc.communicate(timeout=timeout)
    except BaseException:
        if proc.poll() is None:
            proc.kill()
        proc.wait(timeout=5)
        raise
    if proc.returncode:
        detail = (stderr or stdout or b"psql restore failed").decode("utf-8", errors="replace")[-5000:]
        raise MigrationSafetyError(f"psql restore failed in staging: {detail}")


def _inspect_pg_dump_custom(source: Path, timeout: int) -> BackupDetection:
    binary = shutil.which("pg_restore")
    if not binary:
        raise MigrationSafetyError("pg_restore is missing from the ManubisGuard runtime image.")
    result = subprocess.run(
        [binary, "--list", str(source)],
        env=_cli_env("postgresql://localhost/postgres"),
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )
    if result.returncode:
        detail = (result.stderr or result.stdout or "pg_restore inspection failed")[-4000:]
        raise MigrationSafetyError(f"pg_restore inspection failed: {detail}")

    sample = (result.stdout or "").lower()
    evidence = ["pg_restore TOC inspection completed"]
    marker_hits = [marker for marker in ("pasarguard", "pasar guard") if marker in sample]
    has_timescale = "timescaledb" in sample or "_timescaledb_catalog" in sample
    if marker_hits:
        product = "pasarguard"
        confidence = "high"
        evidence.extend(f"legacy marker in dump TOC: {marker}" for marker in marker_hits)
    elif all(table in sample for table in ("core_configs", "nodes", "alembic_version")):
        product = "pasarguard"
        confidence = "medium"
        evidence.append("schema markers found in pg_restore TOC")
    else:
        product = "unknown"
        confidence = "low"
    if has_timescale:
        evidence.append("TimescaleDB objects found in pg_restore TOC")
    revision_match = re.search(r"alembic_version.*?([0-9a-z]{8,32})", sample, flags=re.DOTALL)
    return BackupDetection(
        path=str(source),
        format="pg_dump_custom",
        source_product=product,
        confidence=confidence,
        evidence=tuple(dict.fromkeys(evidence)),
        schema_revision=revision_match.group(1) if revision_match else None,
        warnings=("Custom PostgreSQL dump was identified from its read-only TOC.",),
    )


def _filtered_pg_restore_list(source: Path, dest: Path, timeout: int) -> Path:
    binary = shutil.which("pg_restore")
    if not binary:
        raise MigrationSafetyError("pg_restore is missing from the ManubisGuard runtime image.")
    result = subprocess.run(
        [binary, "--list", str(source)],
        env=_cli_env("postgresql://localhost/postgres"),
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )
    if result.returncode:
        raise MigrationSafetyError(
            (result.stderr or result.stdout or "pg_restore --list failed")[-4000:]
        )
    lines = []
    for line in (result.stdout or "").splitlines():
        low = line.lower()
        if "extension" in low and "timescaledb" in low:
            continue
        lines.append(line)
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return dest


def _run_pg_restore(
    source: Path,
    url: str,
    timeout: int,
    *,
    timescale: bool,
) -> None:
    binary = shutil.which("pg_restore")
    if not binary:
        raise MigrationSafetyError("pg_restore is missing from the ManubisGuard runtime image.")
    with tempfile.TemporaryDirectory(prefix="manubisguard-pgrestore-") as tmp:
        args = [
            binary,
            *_cli_args(url),
            "--exit-on-error",
            "--no-owner",
            "--no-privileges",
        ]
        if timescale:
            list_file = _filtered_pg_restore_list(
                source, Path(tmp) / "restore.list", min(timeout, 120)
            )
            args += ["--use-list", str(list_file)]
        args.append(str(source))
        result = subprocess.run(
            args,
            env=_cli_env(url),
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    if result.returncode:
        detail = (result.stderr or result.stdout or "pg_restore failed")[-5000:]
        raise MigrationSafetyError(f"pg_restore failed in staging: {detail}")


def inspect_backup_source(path: str | Path) -> tuple[Path, BackupDetection, tempfile.TemporaryDirectory[str] | None]:
    source, detection, tmp = _prepare_source(Path(path).expanduser().resolve())
    return source, detection, tmp


def restore_backup_into_staging(
    backup_path: str | Path,
    staging: StagingDatabase,
    *,
    timeout: int = 900,
    allow_external_staging: bool = False,
) -> BackupDetection:
    assert_staging_target(
        staging._production_url,
        staging.staging_url,
        allow_external_port=allow_external_staging,
    )
    path = Path(backup_path).expanduser().resolve()
    if not path.is_file():
        raise FileNotFoundError(path)

    source, detection, tmp = _prepare_source(path)
    try:
        if detection.format == "pg_dump_custom":
            detection = _inspect_pg_dump_custom(source, min(timeout, 120))
        if not detection.is_pasarguard or detection.confidence not in {"high", "medium"}:
            raise MigrationSafetyError("Backup is not positively identified as PasarGuard.")
        if detection.format in {"sql", "sql.gz"}:
            _assert_sql_dump_complete(source)

        uses_timescale = _backup_uses_timescaledb(source, detection)
        post_restore_needed = uses_timescale
        if uses_timescale:
            _timescale_pre_restore(staging.staging_url)
        try:
            if detection.format == "sql":
                if uses_timescale:
                    with tempfile.TemporaryDirectory(prefix="manubisguard-ts-sql-") as work:
                        prepared = Path(work) / "filtered.sql"
                        from app.migration.timescale import prepare_timescale_sql_file

                        prepare_timescale_sql_file(source, prepared)
                        _run_psql_restore(prepared, staging.staging_url, compressed=False, timeout=timeout)
                else:
                    _run_psql_restore(source, staging.staging_url, compressed=False, timeout=timeout)
            elif detection.format == "sql.gz":
                if uses_timescale:
                    with tempfile.TemporaryDirectory(prefix="manubisguard-ts-sql-") as work:
                        prepared = Path(work) / "filtered.sql"
                        from app.migration.timescale import prepare_timescale_sql_gzip

                        prepare_timescale_sql_gzip(source, prepared)
                        _run_psql_restore(prepared, staging.staging_url, compressed=False, timeout=timeout)
                else:
                    _run_psql_restore(source, staging.staging_url, compressed=True, timeout=timeout)
            elif detection.format == "pg_dump_custom":
                _run_pg_restore(source, staging.staging_url, timeout, timescale=uses_timescale)
            else:
                raise MigrationSafetyError(f"Unsupported database restore format: {detection.format}")
        finally:
            if post_restore_needed:
                _timescale_post_restore(staging.staging_url)
        return detection
    finally:
        if tmp is not None:
            tmp.cleanup()


def upgrade_staging_database(
    staging: StagingDatabase,
    *,
    production_url: str,
    revision: str = "head",
    allow_external_staging: bool = False,
) -> None:
    assert_staging_target(
        production_url,
        staging.staging_url,
        allow_external_port=allow_external_staging,
    )
    config = Config(str(Path(__file__).resolve().parents[2] / "alembic.ini"))
    config.set_main_option("sqlalchemy.url", staging.staging_url)
    config.attributes["manubisguard_migration_staging"] = True
    try:
        command.upgrade(config, revision)
    except Exception as exc:
        raise MigrationSafetyError(f"ManubisGuard Alembic migration failed in staging: {exc}") from exc
