export const REPO_URL = 'https://github.com/arsamnikzaad/pasarguard-panel-awg'
export const ORGANIZATION_URL = 'https://github.com/arsamnikzaad'
export const DONATION_URL = '#'
export const DISCUSSION_GROUP = '#'
export const DOCUMENTATION = '#'
