export const REPO_URL = 'https://github.com/ManubisGuard/panel'
export const ORGANIZATION_URL = 'https://github.com/ManubisGuard'
export const DONATION_URL = 'https://donate.manubisguard.org'
export const DISCUSSION_GROUP = 'https://t.me/Pasar_Guard'
export const DOCUMENTATION = 'https://docs.manubisguard.org'
